apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: piyushrrathor/auth
          env: # command that we run=> kubectl create secret generic secrets --from-literal=JWT_KEY=<secret>
            - name: JWT_KEY #we are going to access with this name
              valueFrom:
                secretKeyRef:
                  name: secrets # object name that we that we took while hitting command
                  key: JWT_KEY # with this name we update the data
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
